name       : python-tqdm
version    : 4.23.4
release    : 1
source     :
    - https://github.com/tqdm/tqdm/archive/v4.23.4.tar.gz : dc7f7afb7de8806c8bcfa89a884817e62bdafde73069b2bde8b5b28908d0722c
license    : MIT
component  : programming.python
summary    : Fast, Extensible Progress Meter
description: |
    A fast, extensible progress bar for Python and CLI.
setup      : |
    %python3_setup
install    : |
    %python3_install
