name       : python-tqdm
version    : 4.31.1
release    : 3
source     :
    - https://github.com/tqdm/tqdm/archive/v4.31.1.tar.gz : 524aa635d57deaac538a1fc36fa38a612a51a627fa006ec9ebc1b62698720efb
license    : MIT
component  : programming.python
summary    : Fast, Extensible Progress Meter
description: |
    A fast, extensible progress bar for Python and CLI.
setup      : |
    %python3_setup
install    : |
    %python3_install
