name       : python-tqdm
version    : 4.62.3
release    : 5
source     :
    - https://pypi.io/packages/source/t/tqdm/tqdm-4.62.3.tar.gz : d359de7217506c9851b7869f3708d8ee53ed70a1b8edbba4dbcb47442592920d
license    : MIT
component  : programming.python
summary    : Fast, Extensible Progress Meter
description: |
    A fast, extensible progress bar for Python and CLI.
builddeps  :
    - python-pytest
    - python-setuptools-scm
    - python-toml
enviornment: |
    export SETUPTOOLS_SCM_PRETEND_VERSION=$version
build      : |
    %python3_setup
install    : |
    %python3_install
#check      : |
#    needs newer pytest
#    %python3_test pytest3
